# Generated by Django 4.2.4 on 2024-06-19 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('state', models.CharField(choices=[('INITIAL', 'Инициализировано'), ('UPLOADED', 'Загружено'), ('PROCESSING', 'В процессе'), ('DONE', 'Готово'), ('ERROR', 'Ошибка')], db_index=True, default='INITIAL', verbose_name='Статус')),
                ('original', models.URLField(blank=True, null=True, verbose_name='Оригинал')),
                ('thumb', models.URLField(blank=True, null=True)),
                ('big_thumb', models.URLField(blank=True, null=True)),
                ('big_1920', models.URLField(blank=True, null=True)),
                ('d2500', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Проект')),
            ],
        ),
    ]
