# Generated by Django 4.2.4 on 2024-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_image_file_alter_image_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='big_1920_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='big_thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='d2500_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
