# Generated by Django 4.2.4 on 2024-06-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_image_big_1920_image_image_big_thumb_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
