# Generated by Django 4.2.4 on 2024-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_image_thumb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='big_1920_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='big_thumb_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='d2500_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumb_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='big_1920',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='big_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='d2500',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Оригинал'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
