version: '3'

services:
  db_s3:
    restart: always
    container_name: db_s3
    image: postgres:13.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_s3_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.5-alpine
    hostname: worker
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis
      - db_s3
    environment:
#      - DB_HOST=database
#      - DB_NAME=dbname
#      - DB_USER=dbuser
#      - DB_PASS=pass
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_LOCAL_PORT: ${POSTGRES_LOCAL_PORT}
      POSTGRES_PORT: ${POSTGRES_LOCAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db_s3

  s3_backend:
    container_name: s3_backend
    build:
     context: .
     dockerfile: Dockerfile
    # entrypoint: /entrypoint.sh
    # command: bash -c "python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    environment:
     POSTGRES_NAME: ${POSTGRES_NAME}
     POSTGRES_LOCAL_PORT: ${POSTGRES_LOCAL_PORT}
     POSTGRES_PORT: ${POSTGRES_LOCAL_PORT}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_HOST: db_s3

    expose:
     - "${DJANGO_PORT}"
    volumes:
     - .:/django_app
     - static_volume:/app/public/static
     - media_volume:/app/public/media
    depends_on:
     - db_s3
    restart: on-failure

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/public/static
      - media_volume:/app/public/media

    ports:
      - "8080:80"
    depends_on:
      - s3_backend

volumes:
  db_s3_data:
  static_volume:
  media_volume: